export const SET_VIDEO_SRC = 'SET_VIDEO_SRC'
export const ASYNC_SET_RECTANGLES = 'ASYNC_SET_RECTANGLES'
export const FETCH_RECTANGLES_DATA = 'FETCH_RECTANGLES_DATA'
export const FETCH_VIDEO_SRC = 'FETCH_VIDEO_SRC'